# Generated by Django 4.2.22 on 2025-06-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_instructor_remove_instructor_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='Old courses', max_length=20),
            preserve_default=False,
        ),
    ]
