# Generated by Django 4.2.22 on 2025-07-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='role_type',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('TA', 'TA'), ('owner', 'Owner')], default='instructor', max_length=20),
        ),
    ]
