# Generated by Django 4.2.22 on 2025-07-18 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('grading_time', models.DateTimeField(auto_now=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('question_scores', models.JSONField(default=dict)),
                ('submitted_file', models.FileField(blank=True, null=True, upload_to='submitted_code/')),
                ('submitted_code_text', models.TextField(blank=True, null=True)),
                ('submitted_files_json', models.JSONField(blank=True, null=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='assignments.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('position', models.CharField(help_text='Position reference in the submission', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by_student', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='grading.grade')),
            ],
        ),
    ]
