# Generated by Django 4.2.22 on 2025-06-24 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_gradingresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradingResult',
        ),
    ]
