# Generated by Django 4.2.22 on 2025-06-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_delete_gradingresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to='submitted_code/'),
        ),
    ]
