# Generated by Django 4.2.22 on 2025-06-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_grade_submitted_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='submitted_code_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
