# Generated by Django 4.2.22 on 2025-07-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_grade_submitted_code_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='submitted_files_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
