# Generated by Django 4.2.22 on 2025-07-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0006_grade_submitted_files_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='grade',
            name='question_scores',
            field=models.JSONField(default=dict),
        ),
    ]
