# Generated by Django 4.2.22 on 2025-07-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0007_feedback_metadata_grade_question_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='auto_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='total_points_possible',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
