# Generated by Django 4.2.22 on 2025-07-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0008_grade_auto_points_grade_total_points_possible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='total_points_possible',
        ),
        migrations.AddField(
            model_name='grade',
            name='auto_max_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='rubric_max_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='question_scores',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
