# Generated by Django 4.2.22 on 2025-07-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0009_remove_grade_total_points_possible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='question_scores',
            field=models.JSONField(default=dict),
        ),
    ]
