# Generated by Django 4.2.22 on 2025-07-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0010_alter_grade_question_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='question_scores',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
