# Generated by Django 4.2.22 on 2025-07-18 21:56

from django.db import migrations, models
import django.db.models.deletion
import grade_gator.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('grade_method', models.CharField(blank=True, choices=[('POINTS', 'Points Based'), ('PERCENT', 'Percentage Based'), ('LETTER', 'Letter Grade'), ('STANDARDS', 'Standards Based')], default='POINTS', max_length=10)),
                ('points', models.IntegerField(default=0)),
                ('due_date', models.DateTimeField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_visible_to_students', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_manually_graded', models.BooleanField(default=False)),
                ('questions', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='GradingRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('rubric_file', models.FileField(blank=True, null=True, storage=grade_gator.storage_backends.ProfessorTestCasesStorage(), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_time', models.PositiveIntegerField(default=0, help_text='Extra time in minutes')),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('custom_due_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='student-submissions/')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, storage=grade_gator.storage_backends.UngradedSubmissionsStorage(), upload_to='')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assignments.submission')),
            ],
        ),
    ]
