# Generated by Django 5.1.7 on 2025-03-15 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('questions', models.TextField()),
                ('grade_method', models.CharField(choices=[('POINTS', 'Points Based'), ('PERCENT', 'Percentage Based'), ('LETTER', 'Letter Grade'), ('STANDARDS', 'Standards Based')], default='POINTS', max_length=10)),
                ('scoring_breakdown', models.TextField()),
                ('timing', models.CharField(max_length=50)),
                ('due_date', models.DateTimeField()),
                ('is_visible_to_students', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_time', models.PositiveIntegerField(default=0, help_text='Extra time in minutes')),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('custom_due_date', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_accommodations', to='assignments.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_accommodations', to='courses.student')),
            ],
            options={
                'unique_together': {('student', 'assignment')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('files', models.FileField(help_text='Uploaded PDF file', upload_to='submissions/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.student')),
            ],
            options={
                'unique_together': {('student', 'assignment')},
            },
        ),
    ]
