# Generated by Django 5.1.7 on 2025-03-16 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='submission',
            name='code_file',
            field=models.FileField(blank=True, null=True, upload_to='student-submissions/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='pdf_files',
            field=models.FileField(blank=True, null=True, upload_to='pdf-submissions/'),
        ),
        migrations.CreateModel(
            name='GradingRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('rubric_file', models.FileField(blank=True, null=True, upload_to='grading-rubrics/')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='assignments.assignment')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='courses.instructor')),
            ],
        ),
        migrations.RemoveField(
            model_name='submission',
            name='files',
        ),
    ]
