# Generated by Django 4.2.22 on 2025-10-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='autograder_name',
            field=models.CharField(null=True),
        ),
    ]
