# Generated by Django 4.2.22 on 2025-10-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_submission_status_alter_assignment_autograder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(blank=True, default='not submitted', max_length=20, null=True),
        ),
    ]
