# Generated by Django 5.1.7 on 2025-04-16 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_submission_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='code_file',
            new_name='submission_file',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='pdf_files',
        ),
    ]
