# Generated by Django 4.2.19 on 2025-04-21 20:05
import assignments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_rename_code_file_submission_submission_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='scoring_breakdown',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='timing',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_file',
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_manually_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignment',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='grade_method',
            field=models.CharField(blank=True, choices=[('POINTS', 'Points Based'), ('PERCENT', 'Percentage Based'), ('LETTER', 'Letter Grade'), ('STANDARDS', 'Standards Based')], default='POINTS', max_length=10),
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=assignments.models.submission_upload_path)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assignments.submission')),
            ],
        ),
    ]
