# Generated by Django 4.2.21 on 2025-05-28 21:01

from django.db import migrations, models
import grade_gator.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_rename_title_assignment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingrubric',
            name='rubric_file',
            field=models.FileField(blank=True, null=True, storage=grade_gator.storage_backends.ProfessorTestCasesStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(blank=True, null=True, storage=grade_gator.storage_backends.UngradedSubmissionsStorage(), upload_to=''),
        ),
    ]
