# Generated by Django 4.2.22 on 2025-07-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_gradingrubric_rubric_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='student-submissions/'),
        ),
    ]
