# Generated by Django 4.2.22 on 2025-07-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_submission_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='questions',
            field=models.JSONField(default=list),
        ),
    ]
