# Generated by Django 4.2.22 on 2025-07-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_assignment_allow_late_submissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
