# Generated by Django 4.2.22 on 2025-07-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_alter_assignment_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='autograder_name',
            field=models.CharField(null=True),
        ),
    ]
